---
name: NoDrops
version: 4.20.69
main: MCA7\NoDrops\Main
api: [ 4.0.0, 5.0.0 ]
website: https://github.com/MCPEAbdu77/NoDropsPE

commands:
  toggledrops:
    description: "toggle NoDrops"
    permission: nodropspe.command
  trash:
    description: "Removes item from inventory"
    permission: nodropspe.trash
  trashbin:
    description: "Removed item from inventory"
    permission: nodropspe.trash
  drop:
    description: "Hold the item and use to drop items"
    permission: nodropspe.drop
  dropitem:
    description: "Hold the item and use to drop items"
    permission: nodropspe.drop

permissions:
  nodropspe.command:
    default: op
  nodropspe.drop:
    default: true
  nodropspe.trash:
    default: true
...
