---
name: NoDrops
version: 4.20.69
main: MCA7\NoDrops\Main
api: [ 4.0.0, 5.0.0 ]
website: https://github.com/MCPEAbdu77/NoDropsPE

commands:
  toggledrops:
    description: "toggle NoDrops"
    permission: nodropspe.command
  trash:
    description: "Removes item from inventory"
  trashbin:
    description: "Removed item from inventory"
  drop:
    description: "Hold the item and use to drop items"
  dropitem:
    description: "Hold the item and use to drop items"

permissions:
  nodropspe.command:
    default: op
...
